-- PostgreSQL database dump for crime_ai

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Drop tables if exist for clean restore
DROP TABLE IF EXISTS public.chat_history CASCADE;
DROP TABLE IF EXISTS public.predictions CASCADE;
DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.criminals CASCADE;
DROP TABLE IF EXISTS public.officers CASCADE;
DROP TABLE IF EXISTS public.crime_records CASCADE;
DROP TABLE IF EXISTS public.crimes CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

--
-- TOC entry 218 (class 1259 OID 16498)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'OFFICER'::character varying, 'ANALYST'::character varying, 'USER'::character varying])::text[])))
);

ALTER TABLE public.users OWNER TO postgres;

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 224 (class 1259 OID 16525)
-- Name: crimes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crimes (
    id bigint NOT NULL,
    category character varying(255),
    crime_name character varying(255),
    description character varying(255),
    severity character varying(255)
);

ALTER TABLE public.crimes OWNER TO postgres;

ALTER TABLE public.crimes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crimes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 220 (class 1259 OID 16509)
-- Name: crime_records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crime_records (
    id bigint NOT NULL,
    city character varying(255),
    crime_date date,
    crime_type character varying(255),
    description character varying(255),
    location character varying(255),
    severity character varying(255),
    state character varying(255),
    status character varying(255),
    crime_id bigint NOT NULL
);

ALTER TABLE public.crime_records OWNER TO postgres;

ALTER TABLE public.crime_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crime_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 222 (class 1259 OID 16517)
-- Name: officers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.officers (
    id bigint NOT NULL,
    badge_number character varying(255),
    department character varying(255),
    email character varying(255),
    name character varying(255),
    phone_number character varying(255),
    rank character varying(255)
);

ALTER TABLE public.officers OWNER TO postgres;

ALTER TABLE public.officers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.officers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 226 (class 1259 OID 16538)
-- Name: criminals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.criminals (
    id bigint NOT NULL,
    address character varying(255),
    age integer,
    alias character varying(255),
    criminal_status character varying(255),
    description character varying(255),
    gender character varying(255),
    name character varying(255),
    phone_number character varying(255)
);

ALTER TABLE public.criminals OWNER TO postgres;

ALTER TABLE public.criminals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.criminals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 228 (class 1259 OID 16546)
-- Name: predictions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.predictions (
    id bigint NOT NULL,
    city character varying(255),
    confidence_score double precision,
    crime_type character varying(255),
    description character varying(255),
    predicted_risk character varying(255),
    prediction_date timestamp(6) without time zone,
    state character varying(255),
    crime_id bigint
);

ALTER TABLE public.predictions OWNER TO postgres;

ALTER TABLE public.predictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.predictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 230 (class 1259 OID 16559)
-- Name: reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports (
    id bigint NOT NULL,
    description character varying(255),
    file_path character varying(255),
    generated_at timestamp(6) without time zone,
    generated_by character varying(255),
    report_name character varying(255),
    report_type character varying(255)
);

ALTER TABLE public.reports OWNER TO postgres;

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 232 (class 1259 OID 16567)
-- Name: chat_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_history (
    id bigint NOT NULL,
    ai_response character varying(255),
    "timestamp" timestamp(6) without time zone,
    user_message character varying(255),
    user_id bigint NOT NULL
);

ALTER TABLE public.chat_history OWNER TO postgres;

ALTER TABLE public.chat_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Data Insertion
--

COPY public.users (id, email, name, password, role) FROM stdin;
1	yadnyesh@example.com	Yadnyesh	$2a$10$xKf2wf.x8M9Xr4KtVgtZ2uZeUJEBlISLffZmeGYHJt2oUKXsVt8Nq	USER
\.

COPY public.crimes (id, category, crime_name, description, severity) FROM stdin;
2	Cyber Crime	Cybercrime	Crimes involving computers, networks, or digital systems	High
3	Cyber Crime	Cybercrime	Crimes involving computers, networks, or digital systems	High
4	Cyber Crime	Cybercrime	Crimes involving computers, networks, or digital systems	High
5	\N	\N	Vehicle theft reported	High
6	\N	\N	Vehicle theft reported	High
7	Cyber Crime	Cybercrime	Crimes involving computers, networks, or digital systems	High
8	Cyber Crime	Cybercrime	Crimes involving computers, networks, or digital systems	High
9	Cyber Crime	Cybercrime	Crimes involving computers, networks, or digital systems	High
\.

COPY public.crime_records (id, city, crime_date, crime_type, description, location, severity, state, status, crime_id) FROM stdin;
1	Pune	2026-07-21	Theft	Vehicle theft reported	Ravet	High	Maharashtra	Unsolved	2
2	Pune	2026-07-21	Cybercrime	Online financial fraud incident	Hinjewadi	High	Maharashtra	Open	2
\.

--
-- Sequence Sets
--

SELECT pg_catalog.setval('public.chat_history_id_seq', 1, true);
SELECT pg_catalog.setval('public.crime_records_id_seq', 2, true);
SELECT pg_catalog.setval('public.crimes_id_seq', 9, true);
SELECT pg_catalog.setval('public.criminals_id_seq', 1, true);
SELECT pg_catalog.setval('public.officers_id_seq', 1, true);
SELECT pg_catalog.setval('public.predictions_id_seq', 1, true);
SELECT pg_catalog.setval('public.reports_id_seq', 1, true);
SELECT pg_catalog.setval('public.users_id_seq', 1, true);

--
-- Primary Keys & Constraints
--

ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY public.crimes ADD CONSTRAINT crimes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.crime_records ADD CONSTRAINT crime_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.officers ADD CONSTRAINT officers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.criminals ADD CONSTRAINT criminals_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.predictions ADD CONSTRAINT predictions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reports ADD CONSTRAINT reports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.chat_history ADD CONSTRAINT chat_history_pkey PRIMARY KEY (id);

--
-- Foreign Keys
--

ALTER TABLE ONLY public.crime_records ADD CONSTRAINT fk_crime_records_crime FOREIGN KEY (crime_id) REFERENCES public.crimes(id);
ALTER TABLE ONLY public.predictions ADD CONSTRAINT fk42i0vlu4d48cosh0ba18rshbs FOREIGN KEY (crime_id) REFERENCES public.crimes(id);
ALTER TABLE ONLY public.chat_history ADD CONSTRAINT fkqw6yblcx0hqkn34q6jg03bj8 FOREIGN KEY (user_id) REFERENCES public.users(id);
