package com.crimeanalytics.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
public class ReportRequest {

    @NotBlank(message = "Report name is required")
    private String reportName;

    @NotBlank(message = "Report type is required")
    private String reportType;

    @NotBlank(message = "Generated by is required")
    private String generatedBy;

    @NotNull(message = "Generated date is required")
    private LocalDateTime generatedAt;

    private String filePath;

    private String description;
}